Insert x-axis does not work
jbkieffer/intro-data-viz pull request #21
Opened 2022-07-28 21:01 UTC by RobJamesRamos

Fixes #8

2022-07-28 21:24 UTC, jbkieffer commented on episodes/03-communicating-the-message.md
> +We can now specify the data for our x -axis. Google sheets will not let you set the x-axis directly from your data table. This is likely a bug, but we can work around it by adding our x-axis data as
```suggestion
Suggest updating to one sentence for clarity: "Once the Select data range menu is open, you can click..."
```

```suggestion
Update it's to its in the last sentence
```

2022-07-28 21:26 UTC, jbkieffer requested changes
This looks good! I am adding a few language tweaks.

2022-07-31 15:37 UTC, RobJamesRamos commented
Incorporated the recommended changes.

2022-08-05 14:03 UTC, jbkieffer approved these changes

2022-08-05 14:03 UTC, merged